
POST http://127.0.0.1:8080/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "020729aa",
  "fcmToken": "test-fcm-token"
}

###

### 알림 설정 조회
GET http://127.0.0.1:8080/settings/reminder

### 알림 설정 변경
PUT http://127.0.0.1:8080/settings/reminder
Content-Type: application/json

{
  "enabled": true,
  "meridiem": "PM",
  "hour": 9,
  "minute": 30
}

### 알림 해제
PUT http://127.0.0.1:8080/settings/reminder/disable

### FCM 토큰 등록
POST http://127.0.0.1:8080/settings/fcmtoken
Content-Type: application/json

{
  "fcmToken": "test-fcm-token"
}


### 마이페이지 메인 조회
GET http://127.0.0.1:8080/users/me